package top.jingwenmc.mqeasy.api.message;

public enum MessageType {
    SERVER_WITH_RETURN,SERVER_NO_RETURN, BUKKIT_PLAYER_WITH_RETURN, BUKKIT_PLAYER_NO_RETURN
    ,RETURNING_MESSAGE_SERVER, RETURNING_MESSAGE_BUKKIT_PLAYER
    , BUNGEE_PLAYER_NO_RETURN, BUNGEE_PLAYER_WITH_RETURN, RETURNING_MESSAGE_BUNGEE_PLAYER
}
